import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

export type ContractPdfProps = {
  title: string;
  body: string;
  businessName: string | null;
  photographerName: string | null;
  clientName: string | null;
  projectTitle: string | null;
  contractId: string;
  createdAt: string;
  customFields: Array<{ key: string; value: string }>;
};

const styles = StyleSheet.create({
  page: {
    padding: 56,
    fontFamily: 'Helvetica',
    fontSize: 10.5,
    color: '#111111',
    lineHeight: 1.5,
  },
  header: {
    borderBottomWidth: 0.5,
    borderBottomColor: '#888888',
    paddingBottom: 16,
    marginBottom: 28,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  businessName: {
    fontSize: 14,
    fontFamily: 'Helvetica-Bold',
    color: '#111111',
    letterSpacing: 0.5,
  },
  meta: {
    fontSize: 9,
    color: '#555555',
    textAlign: 'right',
  },
  title: {
    fontSize: 18,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 20,
    color: '#111111',
  },
  subline: {
    fontSize: 9,
    color: '#555555',
    marginBottom: 28,
  },
  body: {
    fontSize: 10.5,
    color: '#111111',
    whiteSpace: 'pre-wrap',
  },
  customSection: {
    marginTop: 24,
    paddingTop: 16,
    borderTopWidth: 0.5,
    borderTopColor: '#cccccc',
  },
  customTitle: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 10,
  },
  customRow: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  customKey: {
    width: 120,
    fontFamily: 'Helvetica-Bold',
    color: '#555555',
  },
  customValue: {
    flex: 1,
  },
  footer: {
    position: 'absolute',
    bottom: 32,
    left: 56,
    right: 56,
    fontSize: 8,
    color: '#888888',
    borderTopWidth: 0.5,
    borderTopColor: '#cccccc',
    paddingTop: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
});

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

export function ContractPdf(props: ContractPdfProps) {
  const header =
    props.businessName ?? props.photographerName ?? 'Photography Services';

  const subline = [
    props.clientName ? `Client: ${props.clientName}` : null,
    props.projectTitle ? `Project: ${props.projectTitle}` : null,
  ]
    .filter(Boolean)
    .join(' · ');

  return (
    <Document
      title={props.title}
      author={props.photographerName ?? undefined}
      subject="Photography services agreement"
    >
      <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.businessName}>{header}</Text>
          <View style={styles.meta}>
            <Text>Contract · {props.contractId.slice(0, 8)}</Text>
            <Text>{formatDate(props.createdAt)}</Text>
          </View>
        </View>

        <Text style={styles.title}>{props.title}</Text>
        {subline ? <Text style={styles.subline}>{subline}</Text> : null}

        <Text style={styles.body}>{props.body}</Text>

        {props.customFields.length > 0 ? (
          <View style={styles.customSection}>
            <Text style={styles.customTitle}>Additional terms</Text>
            {props.customFields.map((f) => (
              <View key={f.key} style={styles.customRow}>
                <Text style={styles.customKey}>{f.key}</Text>
                <Text style={styles.customValue}>{f.value}</Text>
              </View>
            ))}
          </View>
        ) : null}

        <View style={styles.footer} fixed>
          <Text>Generated by {process.env.NEXT_PUBLIC_APP_NAME ?? ''}</Text>
          <Text render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
        </View>
      </Page>
    </Document>
  );
}
